package com.example.network

import android.graphics.Bitmap
import com.example.BuildConfig
import com.example.utils.ImageUtils
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.concurrent.TimeUnit

@JsonClass(generateAdapter = true)
data class GeminiInlineData(
    @Json(name = "mimeType") val mimeType: String,
    @Json(name = "data") val data: String
)

@JsonClass(generateAdapter = true)
data class GeminiPart(
    @Json(name = "text") val text: String? = null,
    @Json(name = "inlineData") val inlineData: GeminiInlineData? = null
)

@JsonClass(generateAdapter = true)
data class GeminiContent(
    @Json(name = "parts") val parts: List<GeminiPart>,
    @Json(name = "role") val role: String? = null
)

@JsonClass(generateAdapter = true)
data class GeminiGenerateRequest(
    @Json(name = "contents") val contents: List<GeminiContent>,
    @Json(name = "systemInstruction") val systemInstruction: GeminiContent? = null
)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(
    @Json(name = "content") val content: GeminiContent? = null,
    @Json(name = "finishReason") val finishReason: String? = null
)

@JsonClass(generateAdapter = true)
data class GeminiGenerateResponse(
    @Json(name = "candidates") val candidates: List<GeminiCandidate>? = null,
    @Json(name = "error") val error: GeminiError? = null
)

@JsonClass(generateAdapter = true)
data class GeminiError(
    @Json(name = "message") val message: String? = null,
    @Json(name = "code") val code: Int? = null,
    @Json(name = "status") val status: String? = null
)

class GeminiService {

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    private val requestAdapter = moshi.adapter(GeminiGenerateRequest::class.java)
    private val responseAdapter = moshi.adapter(GeminiGenerateResponse::class.java)

    companion object {
        private const val MODEL_NAME = "gemini-3.5-flash"
        private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/$MODEL_NAME:generateContent"
    }

    suspend fun askVisualQuestion(
        bitmap: Bitmap,
        question: String,
        cvTelemetryContext: String? = null
    ): Result<String> = withContext(Dispatchers.IO) {
        try {
            val apiKey = BuildConfig.GEMINI_API_KEY
            if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY" || apiKey == "YOUR_API_KEY") {
                return@withContext Result.failure(
                    IllegalStateException("Gemini API key is not configured. Please set GEMINI_API_KEY in the AI Studio Secrets panel.")
                )
            }

            // Convert image to Base64
            val base64Image = ImageUtils.bitmapToBase64(bitmap, quality = 85)

            // Parts list for prompt
            val parts = mutableListOf<GeminiPart>()
            parts.add(GeminiPart(inlineData = GeminiInlineData(mimeType = "image/jpeg", data = base64Image)))

            val fullPrompt = buildString {
                if (!cvTelemetryContext.isNullOrBlank()) {
                    appendLine("You are provided with real computer vision telemetry generated by our local CV engine:")
                    appendLine(cvTelemetryContext)
                    appendLine()
                }
                append("User question about this image: $question")
            }
            parts.add(GeminiPart(text = fullPrompt))

            val systemInstruction = GeminiContent(
                parts = listOf(
                    GeminiPart(
                        text = "You are VisionAI, an intelligent Visual Question Answering system built for a Computer Vision mini-project. " +
                                "You answer questions about the provided image accurately, concisely, and factually. " +
                                "Ground your answers strictly in the visual evidence and any computer vision telemetry provided. " +
                                "Never hallucinate features that do not exist."
                    )
                )
            )

            val requestBodyObj = GeminiGenerateRequest(
                contents = listOf(GeminiContent(parts = parts)),
                systemInstruction = systemInstruction
            )

            val jsonString = requestAdapter.toJson(requestBodyObj)
            val url = "$BASE_URL?key=$apiKey"

            val request = Request.Builder()
                .url(url)
                .post(jsonString.toRequestBody("application/json".toMediaType()))
                .build()

            client.newCall(request).execute().use { response ->
                val bodyStr = response.body?.string() ?: ""
                if (!response.isSuccessful) {
                    val errorObj = try { responseAdapter.fromJson(bodyStr)?.error } catch (e: Exception) { null }
                    val errMsg = errorObj?.message ?: "Gemini API error (HTTP ${response.code}): $bodyStr"
                    return@withContext Result.failure(RuntimeException(errMsg))
                }

                val geminiResp = responseAdapter.fromJson(bodyStr)
                val answer = geminiResp?.candidates?.firstOrNull()?.content?.parts?.firstOrNull { it.text != null }?.text
                if (!answer.isNullOrBlank()) {
                    Result.success(answer.trim())
                } else {
                    Result.failure(RuntimeException("Gemini returned an empty response candidate."))
                }
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun describeImage(
        bitmap: Bitmap,
        cvTelemetryContext: String? = null
    ): Result<String> {
        return askVisualQuestion(
            bitmap = bitmap,
            question = "Provide a comprehensive, clear, and detailed description of what is happening in this image, including key subjects, background setting, spatial arrangement, colors, and noticeable text or objects.",
            cvTelemetryContext = cvTelemetryContext
        )
    }
}
